apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: otel/opentelemetry-collector-contrib:0.109.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:

    exporters:
      otlp:
        endpoint: http://tempo-sample-distributor.default.svc.cluster.local:4317
        tls:
          insecure: true
      debug:
      

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]