apiVersion: v1
kind: Pod
metadata:
  name: myapp
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
spec:
  containers:
  - name: myapp
    image: ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-java:main
    ports:
      - containerPort: 8080
        protocol: TCP